name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag and update Cargo.toml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^version = .*/version = \"$VERSION\"/" Cargo.toml

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build for ARM
        run: cross build --release --target arm-unknown-linux-gnueabihf

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/arm-unknown-linux-gnueabihf/release/sb-healthcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
