name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build for ARM
        run: cross build --release --target arm-unknown-linux-gnueabihf

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/arm-unknown-linux-gnueabihf/release/sb-healthcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
